### ISSUE TITLE
Missing package 'configargparse'

### ISSUE THREAD

**Issue by esidebo** [ac-tuwien/pymhlib#14]
I tried installing and running a demo 

```
$ python -m pymhlib.demos.maxsat
Traceback (most recent call last):
  File "~/anaconda3/envs/skb-ortools/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/anaconda3/envs/skb-ortools/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "~/anaconda3/envs/skb-ortools/lib/python3.9/site-packages/pymhlib/demos/maxsat.py", line 10, in <module>
    from pymhlib.solution import TObj
  File "~/anaconda3/envs/skb-ortools/lib/python3.9/site-packages/pymhlib/solution.py", line 16, in <module>
    from pymhlib.settings import settings, get_settings_parser
  File "~/anaconda3/envs/skb-ortools/lib/python3.9/site-packages/pymhlib/settings.py", line 16, in <module>
    from configargparse import ArgParser, Namespace, ArgumentDefaultsRawHelpFormatter
ModuleNotFoundError: No module named 'configargparse'
```
After installing configargparse I can run the demo successfully.

**Comment by graidl** [comment]
Yes, configargparse is needed, but it is also listed in requirements.txt as a dependency, so I do not see the problem right now. If you checked out the code from the repo and run `pip install -r requirements.txt` this package should also be installed.

**Comment by esidebo** [comment]
Ah OK right, shouldnt that be stressed under the Installation section perhaps?

**Comment by graidl** [comment]
`requirements.txt` is the standard way any Python package uses for specifying its dependencies, and which pip, conda etc. utilize for automatically installing all required packages. I feel that this doesn't need to be explicitly documented here.
